
%----------------------------------------------------------------------
%                      The Participant Selection
%----------------------------------------------------------------------
ParText = double(['Thank you very much for participating in our experiment.\n' ...
                'You have now successfully transferred to the LabMaestro Pack&Go website,\n' ...
                'where the tasks will be administrated. \n' ...
                'Please press a button to continue.']);

ParText2 = double(['In the current experiment, there will be several different\n' ...
                    'attention tests. First, at random times, you will be asked to\n' ...
                    'press a specific key on the keyboard. If you do not respond\n' ...
                    'to these trials, the experiment will end automatically. \n\n' ...
                    'Further, all the stimuli in the current study will\n' ...
                    'be presented in a color frame. Below, you can find an example.\n' ...
                    'In a second type of attention test, you will be asked about the\n' ...
                    'color of the frame of the previous trial. You should respond\n' ...
                    'to these trials as fast as possible. Please make sure\n' ...
                    'that you respond to these trials correctly.\n' ...
                    'Please press a button to continue.\n\n\n\n\n\n\n\n\n']);

%----------------------------------------------------------------------
%                      Sound Checkup
%----------------------------------------------------------------------
SoundText = double(['In the current experiment, you need to hear some auditory stimuli.\n' ...
                    'Currently, some beeps are playing, and you should be able to\n' ...
                    'hear them correctly. If not, please increase the volume on your\n' ...
                    'computer or change the output device to one that can play audio better.\n' ...
                    'Also, make sure that the audio level is not too high, as it should not\n' ...
                    'be harsh. It is suggested that the audio level not be changed after\n' ...
                    'adjusting it here. Also, please make sure that there are no other\n' ...
                    'apps open that can make play notifications and distract you.\n' ...
                    'After you make sure that the audio level is okay, please press Space.']);
SoundTextShort = (['After you make sure that the audio level is okay, please press Space.']);
%----------------------------------------------------------------------
%                      The first sesssion
%----------------------------------------------------------------------
SessionOneText = double(['Thanks again for participating in our experiment. The experiment has\n' ...
                        'three parts and will take approximately one hour. Please make sure that\n' ...
                        'you are in a well-isolated and comfortable environment, and you will not be\n' ...
                        'distracted during this period. In the experiment, you will need to hear\n' ...
                        'and see different colored stimuli. Therefore, please make sure that you\n' ...
                        'can see the stimuli and colors correctly, and if you need any vision\n' ...
                        'correction, such as glasses or contact lenses, please wear them before\n' ...
                        'starting the experiment. Further, if you have several monitors, please make\n' ...
                        'sure to put the experiment on the main one and make your browser full-screen.\n\n' ...
                        'When you are ready, please press a button.']);
%----------------------------------------------------------------------
%                      The Choice task
%----------------------------------------------------------------------
TaskOneText =  double(['In the first part of the experiment, you will participate in two\n' ...
                    'tasks. Please imagine that you are building a toy house for yourself\n' ...
                    'or a kid that you love. In the first task, you will see some toys, one\n' ...
                    'after the other, on the monitor. You need to indicate whether you want\n' ...
                    'to have the toy shown by pressing a corresponding button. In this\n' ...
                    'task, you need to react as fast as possible, and you should trust\n' ...
                    'your gut feelings instead of overthinking your choice.\n\n' ...
                    'To choose NO, you need to press "c", and to choose YES, press "m".\n' ...
                    'Next, you will have several practice trials, where you can get\n' ...
                    'familiarized with the task better. When you are ready to start,\n' ...
                    'please press a button to start the practice.']);

EndofPracticeText = double(['Now, the practice trials are over, and the main experiment starts.\n' ...
                            'Next, you will participate in the choice task. Please remember that you\n' ...
                            'need to choose whether you want to have the presented toy\n' ...
                            'as fast as possible based on your gut feelings.\n' ...
                            'To choose NO, you need to press "c", and to choose YES, press "m".\n' ...
                            'When you are ready to start, please press a button.']);

RestTextOne = double(['Next, you will again participate in the choice task. Please remember that\n' ...
                    'you need to choose whether you want to have the presented toy\n' ...
                    'as fast as possible based on your gut feelings.\n' ...
                    'To choose NO, you need to press "c", and to choose YES, press "m".\n' ...
                    'When you are ready to start, please press a button.']);

RestTextOneBlockThree = double(['Next, you will again participate in the choice task. As you are already familiar\n' ...
                                'with this task, we will start directly with the main experiment. Please remember\n' ...
                                'that you need to choose whether you want to have the presented toy\n' ...
                                'as fast as possible based on your gut feelings.\n' ...
                                'To choose NO, you need to press "c", and to choose YES, press "m".\n' ...
                                'When you are ready to start, please press a button.']);
%----------------------------------------------------------------------
%                      The Preference task
%----------------------------------------------------------------------

TaskTwoText =  double(['In the second task, you will also see some toys one after the other on\n' ...
                        'the monitor. This time, you need to indicate on a scale from 0 (not at all)\n' ...
                        'to 10 (absolutely) how much you like the presented toy.\n' ...
                        'The higher the value you choose, the more you like the toy.\n' ...
                        'To respond, you need to move your mouse cursor, and when you reach\n' ...
                        'the final value, you should press the right mouse button to finalize your\n' ...
                        'response. Next, you will have several practice trials, where you can \n' ...
                        'familiarize yourself with the task better.\n\n' ...
                        'When you are ready, please press a button to start the practice.']);

RestTextTwoOne = double(['Continuing with the main experiment, next, you will participate in the\n' ...
                        'preference task. Please remember that you need to indicate how much you\n' ...
                        'like the presented toy. To respond, you need\n' ...
                        'to use your mouse and choose a value between 0 (not at all) and 10 (absolutely).\n\n' ...
                        'When you are ready to start, please press a button.']);

RestTextTwo = double(['Next, you will participate again in the preference task. Please remember\n' ...
                    'that you need to indicate how much you like the presented toy.\n' ...
                    'To respond, you need to use your mouse and choose\n' ...
                    'a value between 0 (not at all) and 10 (absolutely).\n\n' ...
                    'When you are ready to start, please press a button.']);
%----------------------------------------------------------------------
%                      The third sesssion
%----------------------------------------------------------------------
SessionThreeText = double(['In the third and final part of the experiment, you will participate\n' ...
                            'in three tasks. The first two tasks are the ones that you already\n' ...
                            'had in the first part, and therefore, we will start with the main\n' ...
                            'experiment directly.\n\n' ...
                            'When you are ready to start, please press a button.']);
%----------------------------------------------------------------------
%                      The comparison task
%----------------------------------------------------------------------
TaskThreeText =  double(['In the third task, you will see two toys side-by-side on the monitor\n' ...
                        'simultaneously, from which you need to choose which toy you are more\n' ...
                        'willing to have. In each trial, you need to choose one of the\n' ...
                        'toys. That means, even if you like or do not like both toys, you still\n' ...
                        'need to choose one.\n\n' ...
                        'To choose the toy on the left side, press "c" and for the right one, "m".\n\n' ...
                        'Next, you will have several practice trials to familiarize yourself \n' ...
                        'with the task better. When you are ready, please press a button.']);

RestText = double(['Please rest for a few seconds, and press a button to\n' ...
                    'continue when you are ready.']);
%----------------------------------------------------------------------
%                      The second sesssion
%----------------------------------------------------------------------
LearningText = double(['Now, the second part of the experiment is started. This part consists\n' ...
                        'of two attentional tasks. In these tasks, you need to either respond \n' ...
                        'by pressing a button or keeping a button pressed. The relationship between\n' ...
                        'buttons and responses will be explained to you during practice trials next.\n' ...
                        'Please press a button to continue.']);

LearningPractF = double(['In the approach-avoidance task, you will see toys one after the other,\n' ...
                        'like the tasks in the first part of the experiment. However, this time,\n' ...
                        'you will hear a sound shortly after seeing a toy, based on which\n' ...
                        'you should either approach or avoid the presented toy. \n ' ...
                        'To approach a toy, you need to press "m", and to avoid it, "c".\n' ...
                        'In some trials, there will be no sound; in these trials, you should not\n' ...
                        'press any button.\n' ...
                        'As this task has a shorter response window than previous tasks,\n' ...
                        'you need to respond as fast as possible. The correspondence between\n' ...
                        'sounds and keys will be explained to you next.\n\n' ...
                        'Please press a button to start some practice trials and familiarize\n' ...
                        'yourself with the approach-avoidance task. ']);

LearningPractFOne = double(['When you hear this sound, please press "m" to approach the\n' ...
                            'presented toy. As pressing the key is simulating approaching\n' ...
                            'the toy, you need to press it for longer than usual\n' ...
                            'to be registered.\n' ...
                            'Please try pressing "m" now.']);

LearningPractFTwo = double(['When you hear this sound, please press "c" to avoid the\n' ...
                            'presented toy. As pressing the key is simulating avoiding\n' ...
                            'the toy, you need to press it for longer than usual\n' ...
                            'to be registered.\n' ...
                            'Please try pressing "c" now.']);

LearningPractS = double(['In the emotion-detection task, each toy is followed by an emotional\n' ...
                        'picture. You need to indicate whether the picture presents a positive\n' ...
                        'or negative emotion as fast as possible.\n' ...
                        'In some trials, there will be no emotional image; in these trials, you\n' ...
                        'should not press any button.\n' ...
                        'Note that only your first response will be considered,\n' ...
                        'and you cannot change your response. You will receive\n' ...
                        'feedback after the end of a trial if you respond incorrectly or too slowly.\n' ...
                        'Further, you need to respond by pressing a button once and should not\n' ...
                        'keep it pressed like what you had done for the approach-avoidance task.\n\n' ...
                        'For negative emotions, you need to press "c"\n' ...
                        'and for positive ones, "m." \n\n' ... 
                        'Next, you will participate in several practice\n' ...
                        'trials to learn more about the emotion-detection task.']);

EndOfPracticeLearning = double(['The practice trials are over, and now we start with the \n' ...
                                'main experiment. When you are ready, please press a button.']);

LearbningRestTextOne = double(['Please rest for a couple of seconds. Next, you will again participate\n' ...
                                'in the approach-avoidance task. Reminder: You need to press "c" to avoid \n' ...
                                'a toy and "m" to approach it. When you are ready, please press a button\n' ...
                                'to start.']);

LearbningRestTextTwo = double(['Please rest for a couple of seconds. Next, you will again participate\n' ...
                                'in the emotion-detection task. Reminder: You need to press "c" to indicate a\n' ...
                                'negative image and "m" to indicate a positive one it. When you are ready,\n' ...
                                'please press a button to start.']);

%----------------------------------------------------------------------
%                      rest
%----------------------------------------------------------------------
StopText = double(['Please respond faster!']);

TooShortText = double(['You did not press the button long enough.\n' ...
                    'Please keep the button pressed till you see a fixation cross\n' ...
                    'on the monitor, and then release it.!']);

WrongResponseText = double(['Please pay more attention.\n' ...
                            'Your response was wrong!']);

YesText = double(['Yes']);

NoText = double(['No']);

LikertQues = double(['Empty for now?']);

lowerLikert = double(['0']);

upperLikert = double(['10']);



%----------------------------------------------------------------------
%                      Attention Texts
%----------------------------------------------------------------------

InBetweenText1 = double(['The part of the experiment is finished. Please rest for a couple of\n' ...
                        'seconds, and when you are ready to start the next part, please press\n' ...
                        '"q". Please note that the next part can start only when you press "q",\n' ...
                        'and if you do not correctly respond for more than 3 minutes, the\n' ...
                        'experiment will end automatically.']);

InBetweenText1Short = (['Please press "q" immediately to continue.']);

InBetweenText2 = double(['The part of the experiment is finished. Please rest for a couple of\n' ...
                        'seconds, and when you are ready to start the next part, please press\n' ...
                        '"r". Please note that the next part can start only when you press "r",\n' ...
                        'and if you do not correctly respond for more than 3 minutes, the\n' ...
                        'experiment will end automatically.']);

InBetweenText2Short = (['Please press "r" immediately to continue.']);

InBetweenText3 = double(['The last part of the experiment is finished. Please press\n' ...
                        '"u" to be redirected to the Prolific website. Please note that\n' ...
                        'if you do not correctly respond for more than 3 minutes, the\n' ...
                        'experiment will end automatically.']);

InBetweenText3Short = (['Please press "u" immediately to get redirected.']);

InBetweenTask1 = double(['This is an attention test:\n' ...
                        'please press "a" as soon as possibe.']);
InBetweenTask2 = double(['This is an attention test:\n' ...
                        'please press "d" as soon as possibe.']);
InBetweenTask3 = double(['This is an attention test:\n' ...
                        'please press "g" as soon as possibe.']);
InBetweenTask4 = double(['This is an attention test:\n' ...
                        'please press "k" as soon as possibe.']);

InBetweenTextAttention = double(['If you do not respond in a couple of seconds\n' ...
                                 'the experiment ends automatically']);

UnattentiveText = double(['Unfortunately, the experiment is automatically ended, as you were \n' ...
                        'inattentive for more than a couple of minutes. Thanks for your participation.']);

%----------------------------------------------------------------------
%                      Attention Texts
%----------------------------------------------------------------------
ColorText = double(['This is an attention test:\n' ...
                        'What was the color of the frame of the stimulus you had just seen?\n' ...
                        'Please use the left, down, and right arrow keys to choose, \n' ...
                        'the left, middle, or right option shown below.']);
ColorTextRight = double(['This is an attention test:\n' ...
                        'What was the color of the RIGHT frame of the stimulus you had just seen?\n' ...
                        'Please use the left, down, and right arrow keys to choose, \n' ...
                        'the left, middle, or right option shown below.']);
ColorTextLeft = double(['This is an attention test:\n' ...
                        'What was the color of the LEFT frame of the stimulus you had just seen?\n' ...
                        'Please use the left, down, and right arrow keys to choose, \n' ...
                        'the left, middle, or right option shown below.']);



